# Generated by Django 5.0.4 on 2024-04-06 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_customer_address_alter_customer_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='concluded_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('budgeting', 'Budgeting'), ('approved_budget', 'Approved budget'), ('under_maintenance', 'Under maintenance'), ('concluded', 'Concluded'), ('delivered', 'Delivered')], default='budgeting', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
